### ISSUE TITLE
How to implement wind?

### ISSUE THREAD

**Issue by CypherPotato** [forceprojectx/sslAimAssist#2]
How i can implement game round wind in this project?

**Comment by forceprojectx** [comment]
you will need to sit down with a pencil and paper and just record how wind effects the trajectory and work that into the projectile motion method. as a rule of thumb it looks like every ~11 wind is equal to 1 power, but that may vary based on the selected projectile or other factors. I dont really know

as it sits, in the projectilemotion method of the hack class, the Y value is calculated based on the time of flight for each X value from basically 1 to 1000 which are the horizontal bounds of the game window.
float t represents the time of flight from 0 to that X position

**Comment by Ryouunfuuraku** [comment]
@CypherPotato There are solutions to solve it? I do not know whether you can get the returned data network to give curve analysis.
