### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by TheTyrius** [forceprojectx/sslAimAssist#3]
I recommend MIT. Not including a license means you reserve all rights.

**Comment by forceprojectx** [comment]
tl;dr: If you want it licensed, you license it.

This code is free for use for any purpose without any requirements for attribution. The project is provided in the interest of education and fostering interest in science and mathematics. I am not a lawyer and have no interest in reading all the common licenses and selecting the best one for this project. 

I say again, I am not a lawyer and have no interest in the legal implications and ramifications of licensing.

**Comment by TheTyrius** [comment]
So public domain then. Alright, thank you for the clarification! :)
